# Generated by Django 3.2 on 2021-04-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20210428_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='name',
            new_name='text',
        ),
    ]
