# Generated by Django 3.2 on 2021-05-01 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_pizza_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='owner',
        ),
    ]
